import type { Metadata } from "next";
import "./globals.css";
import "./custom-swiper.css";
import { Bricolage_Grotesque } from 'next/font/google';

export const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={bricolageGrotesque.className}>
        <div>{children}</div>
        </body>
    </html>
  );
}
